### ISSUE TITLE
ndb crashes after launching script

### ISSUE THREAD

**Issue by vaxerski** [GoogleChromeLabs/ndb#204]
Steps to reproduce:
I'm launching ndb with `ndb bot.js` and it launches, starts the script and crashes, the same when i click "start" inside ndb and for example toggle "pause on exceptions" or change tab.

* ndb version: 1.0.37
* Platform / OS version: Microsoft Windows [Version 10.0.17134.407]
* Node.js version: 10.14.1

There seems to be no problem with code since it works on normal node, but when i open it in ndb, then it crashes.

**What happens instead?**

ndb throws:
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:628:16)
    at Rpc.routeMessage_ (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\carlo\rpc\rpc.js:379:9)
    at page_.exposeFunction.data (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\carlo\lib\carlo.js:327:71)
    at Page._onBindingCalled (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Page.js:516:56)
    at CDPSession.Page.client.on.event (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Page.js:134:54)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onMessage (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Connection.js:216:12)
    at Connection._onMessage (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Connection.js:99:19)
    at PipeTransport._dispatch (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\PipeTransport.js:65:24)
    at Socket.PipeTransport._eventListeners.helper.addEventListener.buffer (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\PipeTransport.js:30:64)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:632:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)

I've tried re-installing ndb, reinstalling all dependencies, reinstalling ms build tools, different flags and stuff. It did work, but lately stopped.

I can add that when this started occuring, the ndb got slow, instead of showing my files immediately, it showed them after 10s, and there are windows popping up, which weren't before (node.EXE and npm)

Thanks in advance.

**Comment by ak239** [comment]
popping up windows are fixed in `ndb@1.0.40`.

**Comment by ak239** [comment]
What version of Chrome do you have locally installed?

**Comment by vaxerski** [comment]
Version 70.0.3538.110 (Official) (64-bit)

**Comment by vaxerski** [comment]
maybe it's a problem with my system specifically, tell me what to check if there are any possible causes.

**Comment by vaxerski** [comment]
sorry for the multiple comments but here's a list of things I'd want to add, because they might be helpful in finding the cause.

* My windows C drive has recently got some files NTFS compressed. Idk why, I've reverted most of them and disabled it. Maybe some critical ndb files got affected still? (appdata/npm isn't compressed anymore)
* When launching ndb, it takes AGES to show the project folder despite it being not so large (3k lines of code in main .js file)
* When ndb launches and i wait those AGES for the folder to show up, the CMD takes 70% of CPU, which is pretty much a lot for a script editor, it stops when the folder appears in ndb.

My best guess would be windows NTFS compression since the crashes started occurring randomly and about a week later i found about 25GB of compressed files, so that may be the cause.

If it can be, tell me which files does ndb use for me to check if they aren't compressed.

De-compressed and anti-compress locked folders that may relate to ndb as of right now are:
* project folder
* AppData/roaming/npm
* AppData/roaming/npm-cache
* whole AppData/Local

Hope we can find the cause,
cheers!

**Comment by ak239** [comment]
Thanks a lot for your diagnostic, I will take a look on Windows as soon as I get my windows machine back, it should happen in next day or two.

**Comment by linqOxelar** [comment]
i have the same issue and same message with:

- ndb 1.0.42
- chrome Version 71.0.3578.80 (Build officiel) (64 bits)
- node 10.14.1 and previous

`events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:628:16)
    at Rpc.routeMessage_ (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\carlo\rpc\rpc.js:379:9)
    at page_.exposeFunction.data (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\carlo\lib\carlo.js:380:71)
    at Page._onBindingCalled (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Page.js:516:56)
    at CDPSession.Page.client.on.event (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Page.js:134:54)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onMessage (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Connection.js:216:12)
    at Connection._onMessage (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Connection.js:99:19)
    at PipeTransport._dispatch (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\PipeTransport.js:65:24)
    at Socket.PipeTransport._eventListeners.helper.addEventListener.buffer (C:\Users\user\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\PipeTransport.js:30:64)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:632:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)`


i tried to debug till event.js:167 with nbd, but when i added a breakpoint to this line, ndb added lots of breakpoints of other node modules... so i could not track the bug...
![image](https://user-images.githubusercontent.com/18004866/49551616-2ae09180-f8f0-11e8-87a5-56ccf9cbbf8c.png)

**Comment by vaxerski** [comment]
reverted to ndb@1.0.13 - everything's fine.

**Comment by Yuan-Zi-Yuan** [comment]
yeah，reverted to ndb@1.0.13 ，  everything is OK

**Comment by fdeitelhoff** [comment]
I've the same problem.

ndb@10.26 is working except the breakpoints have no effect at all.

**Comment by ankur123** [comment]
m seeing the same issue 

```
avarshney@avarshneypc MINGW64 ~/Desktop/IR2.0/gitHub/nrf-herder (feat/saved-search)
$ ndb -v
v1.0.42

avarshney@avarshneypc MINGW64 ~/Desktop/IR2.0/gitHub/nrf-herder (feat/saved-search)
$ node -v
v10.15.0

```

**Comment by Mehuge** [comment]
ndb 1.0.44
chrome 73.0.3683.103
node v10.11.0
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed

ndb 1.0.26 works, including breakpoints

**Comment by TimWillis** [comment]
I noticed that any kind of error, and I think warning would cause ndb to
crash. I would run normally with 'node your_server.js' to be able to see
the errors/warnings, fix any errors or warnings, then run with ndb.

**Comment by alexnwalters** [comment]
node v10.15.3
ndb v1.0.44
chrome 74.0.3729.169

I'm installing ndb for the first time and having the same issue, any suggestions on a fix?

**Comment by muzhaqi16** [comment]
I have the same issue. it was working fine with node v10.16.0 and then I removed it and installed 12.4.0 and now after I open it and try to run a script it crashes. I removed it and installed it a couple of times but that didn't work.
```
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:678:16)
    at Rpc.routeMessage_ (C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\carlo\rpc\rpc.js:379:9)
    at C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\carlo\lib\carlo.js:388:71
    at Page._onBindingCalled (C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Page.js:548:56)
    at CDPSession.<anonymous> (C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Page.js:136:54)
    at CDPSession.emit (events.js:200:13)
    at CDPSession._onMessage (C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Connection.js:200:12)
    at Connection._onMessage (C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\Connection.js:112:17)
    at PipeTransport._dispatch (C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\PipeTransport.js:59:22)      
    at Socket.<anonymous> (C:\Users\artan\AppData\Roaming\npm\node_modules\ndb\node_modules\puppeteer-core\lib\PipeTransport.js:30:64)
Emitted 'error' event at:
    at internal/child_process.js:682:35
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

**Comment by alexnwalters** [comment]
not an ideal fix but as someone noted above rolling ndb back seems to work,  I went back to ndb v1.0.26 and it has been working with node v10.15.3

**Comment by ak239** [comment]
One of the possible reasons of this crash was a broken native terminal dependency. I updated it in `ndb@1.0.47` and it should at least not to crash.
Another possible reason is reusing installed Chrome by `carlo`. I am going to force `carlo` to download latest Chromium to address this problem. I will release version with this fix soon (https://github.com/GoogleChromeLabs/ndb/pull/260).

**Comment by ak239** [comment]
Could someone with reproducible issue check out `ndb@1.0.48`? Most problems related to ndb crashes should be fixed there.
This build includes nice way to profile your app as well, just add `--prof` right after `ndb`, e.g. `ndb --prof index.js`.

**Comment by davidlehn** [comment]
Since the ECONNRESET issues point here, I'll add another datapoint that I just updated and get ECONNRESET with 1.0.48+.  1.0.47 works ok.  Is there any particular debug info that would help?

**Comment by ak239** [comment]
@davidlehn could you try to clean install `ndb`? `npm uninstall -g ndb && npm install -g ndb`.
The biggest change after `1.0.47` is that `ndb` fetches chromium by itself and do not reuse installed Chrome. I can assume that something went wrong when `ndb` was fetching Chromium.

What OS do you use?

Another useful information can be get by following steps:
- `mkdir test && cd test`
- `npm init -y && npm install ndb` - it creates new node package and install ndb locally,
- try to run `./node_modules/.bin/ndb`
- if it does not work try to start fetched by `ndb` Chromium, you can find it inside `./node_modules/carlo/lib/.local-data/linux-624492/`, on linux you need to run `./chrome-linux/chrome` from this folder. Does it start?

**Comment by ForsakenHarmony** [comment]
I'm on `1.0.48` and it's still the same error.

First time you try to launch a script nothing happens, when you click again
`Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed`

**Comment by ZeldOcarina** [comment]
I'm having the same error as well, any updates on this?

**Comment by ak239** [comment]
@ZeldOcarina and @ForsakenHarmony could you try steps mentioned in https://github.com/GoogleChromeLabs/ndb/issues/204#issuecomment-505988945 ?
Does puppeteer package work in your environment our of the box? Could you share more details about your environment?
I am going to release next version soon and it will include some other improvements as well.

**Comment by ZeldOcarina** [comment]
@ak239 I've tried executing all of your instructions.
With the latest clean version installed I just get a crash:
![image](https://user-images.githubusercontent.com/42982095/60813409-fc7fa900-a193-11e9-82c5-e7caeea5ed96.png)

With earlier versions as suggested earlier I get the code to be runned but the debugger does not stop on checkpoints, thus useless.

My environment is Windows 10 64bit, I've runned everything with Powershell with admin privileges.

I've installed the Windows toolbox as well.

Can you better explain the puppeteer point? I don't get what you mean? It opens Chromium that should have puppeteer built in by default, right?

Thanks!

**Comment by ak239** [comment]
@ZeldOcarina, thank you. I was able to reproduce it on windows machine yesterday and I know the root of this issue - I will publish fix this week.

**Comment by ZeldOcarina** [comment]
> @ZeldOcarina, thank you. I was able to reproduce it on windows machine yesterday and I know the root of this issue - I will publish fix this week.
> I found that `carlo` spawns new process for backend services with `detached: true` flag and when one of the services tries to do `process.stderr.write` - it fails. It surprisingly works on mac and linux just fine.

Thanks man for your incredible job and what you guys do for the community!

**Comment by ak239** [comment]
@ZeldOcarina could you check `ndb@1.1.0`? (I do not have access to windows machine right now - I will check it this evening).

Thank you for your help! It is critical with platform specific bugs like these.

**Comment by ZeldOcarina** [comment]
![image](https://user-images.githubusercontent.com/42982095/60834839-e7ba0a00-a1c1-11e9-8c3b-ea475596f21e.png)
I've taken my time to test it in different ways, with both global and local installs.
Now the debugger is not crashing but it's still not stopping on errors as you can see in the screenshot.

**Comment by ak239** [comment]
Thanks, @ZeldOcarina. Does `debugger` statement work? I have some idea why breakpoints can be broken on windows, I will debug it this evening. I definitely need to get windows machine and test ndb much better there.

**Comment by ZeldOcarina** [comment]
@ak239 Yes Aleksey with debugger keyword in place the code actually stops. It's only the manual green flags that aren't working!

**Comment by ak239** [comment]
@ZeldOcarina what node version do you use?

I built some similar with your's script and set couple breakpoints there. All of them works as expected. At the same time if you would like to trigger pause on error or exception you can activate pause on exception DevTools [feature](https://umaar.com/dev-tips/32-pause-on-exception/). If you'd like to restart your app - you can use `Ctrl + R`. If you'd like to kill current process without restarting you can hover it in `Node processes` section and click `Kill` button.

You snippet contains a little mistake - it does not require `url` module but uses `url.parse` - I am not sure is it expected in the test or not.

**Comment by ZeldOcarina** [comment]
Thanks @ak239. I've corrected the bug in the code. The breakpoints set with the green flag are not working for me but it's fine, I can use "debuger" keyword to handle this.

Thanks for the tips on `Ctrl + R` and killing the current process.

Now the program is functional and that is what matters the most!

**Comment by hritique** [comment]
Hi, @ak239 I am using node@10.16.0 and ndb@1.1.1 .
I am getting the same issue, the breakpoints are not working but the debugger keyword is working.
![Screenshot (3)](https://user-images.githubusercontent.com/47852078/60966938-0857a080-a337-11e9-9d0c-434c29f445ee.png)

**Comment by ak239** [comment]
@hritique thank you. I believe that I detected problem with breakpoints. It is all about spaces in paths on Windows, DevTools frontend does not replace space with `%20` properly. I will fix it.

**Comment by hritique** [comment]
Thanks @ak239 , I hope it will get fixed.

**Comment by ak239** [comment]
@hritique please try `1.1.2`, it should contain breakpoints fix.

**Comment by ak239** [comment]
This one needs better fix, once and for everything. I will work on it this week. For now I reverted fix from 1.1.2 and publish 1.1.3 without it.
Thanks for your feedback @ZeldOcarina , I think we are close to make windows users happy!

**Comment by ZeldOcarina** [comment]
Thanks @ak239 I'm starting to realize why Windows isn't that popular amongst developers!

**Comment by darcyparker** [comment]
I had same problem on Debian, and found I had to run:
```bash
 sudo sysctl -w kernel.unprivileged_userns_clone=1
```
https://github.com/GoogleChrome/puppeteer/blob/ff6d2a33f3edb8837bde3ab687c6d06510b5d4de/docs/troubleshooting.md#setting-up-chrome-linux-sandbox

In my case it is for a dev machine, so I am not too worried about changing this option.

**Comment by ishaantaylor** [comment]
I'm also having this issue. It fails in the same way after a few seconds. I've been using ndb with this project for a while and have never seen this issue. Could be our project just grew past some limit?

Environment:
- ndb version: 1.1.5
- Platform / OS version: macOS 10.14.5
- Node.js version: 10.16.0

Problem:
```
➜  ndb
/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/lib/process_utility.js:14
    throw error;
    ^

Error: Error: CharacterIdMap ran out of capacity!
Error: CharacterIdMap ran out of capacity!
    at Common.CharacterIdMap.toChar (https://domain/ndb.js:1:141718)
    at https://domain/ndb.js:3:160732
    at Array.map (<anonymous>)
    at Persistence.PathEncoder.encode (https://domain/ndb.js:3:160711)
    at Persistence.Automapping.FilePathIndex.addPath (https://domain/ndb.js:3:142687)
    at Persistence.Automapping._onUISourceCodeAdded (https://domain/ndb.js:3:137592)
    at https://domain/ndb.js:3:135752
    at Workspace.Workspace.dispatchEventToListeners (https://domain/ndb.js:1:91157)
    at Persistence.FileSystemWorkspaceBinding.FileSystem.addUISourceCode (https://domain/ndb.js:1:658133)
    at Persistence.FileSystemWorkspaceBinding.FileSystem._fileChanged (https://domain/ndb.js:3:134868)
    at Rpc.dispatchMessageLocally_ (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:423:16)
    at Rpc.routeMessage_ (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:371:12)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at Rpc.routeMessage_ (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/carlo/rpc/rpc.js:379:9)
    at page_.exposeFunction.data (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/carlo/lib/carlo.js:388:71)
    at Page._onBindingCalled (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:548:56)
    at CDPSession.Page.client.on.event (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Page.js:136:54)
    at CDPSession.emit (events.js:198:13)
    at CDPSession._onMessage (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:200:12)
    at Connection._onMessage (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/Connection.js:112:17)
    at PipeTransport._dispatch (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/PipeTransport.js:59:22)
    at Socket.PipeTransport._eventListeners.helper.addEventListener.buffer (/Users/ishaantaylor/.nvm/versions/node/v10.16.0/lib/node_modules/ndb/node_modules/puppeteer-core/lib/PipeTransport.js:30:64)
Emitted 'error' event at:
    at process.nextTick (internal/child_process.js:640:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by penkong** [comment]
i had same problem with npm (os fedora 32 workstation) 
solution worked for me : delete node_modules and related stuff.
use yarn to re install, and run ndb with yarn.

**Comment by maddie-j** [comment]
I think https://github.com/GoogleChromeLabs/ndb/issues/290 is the same as this. I'm having this issue on MacOS and `ndb` `v1.1.5` as well. I put some of my pokings in the other thread.

**Comment by shapkarin** [comment]
Does anyone solve that?

**Comment by Mehuge** [comment]
> Does anyone solve that?

Both ndb 1.1.4 and 1.1.5 work for me on macOS Catalina

**Comment by shapkarin** [comment]
@Mehuge I have v1.1.5 but looks like this current issue is `not related to ndb` itself. But I hope to get some info from people that solved it somehow.

**Comment by att14** [comment]
I am getting a similar issue after upgrading to macOS Big Sur from macOS Catalina. No problems on Catalina. I'm running `ndb v1.1.5`, `node v14.16.0`, `macOS v11.2.3`, and `Chromium 73.0.3679.0`.

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by liuliangsir** [comment]
@att14 try [this solution](https://github.com/GoogleChromeLabs/ndb/issues/312#issuecomment-653834893).
